### ISSUE TITLE
Create recorders for candidates

### ISSUE THREAD

**Issue by poornaraob** [EnCiv/undebate#113]
Depends on issue #112. 

- [x] Get the moderator recordings from will
- [x] Add links to candidate spreadsheet
- [x] Upload spreadsheet to Klaviyo with @MMitsuyasu and coordinate the column names.
- [x] Email Candidates

**Comment by ddfridley** [comment]
Add links to candidate spreadshet
Upload spreadsheet to Klaviyo with @MMitsuyasu and coordinate the column names.

**Comment by ddfridley** [comment]
done in push #125 
Candidate were wailed on 3/31.
