### ISSUE TITLE
Posting of recorded candidate conversation on social media & other media communication

### ISSUE THREAD

**Issue by poornaraob** [EnCiv/undebate#114]
Explore the venues to post the recorded candidate conversations on social media and other media of communication
- [ ] Talk w/ Radio & TV about PSAs (Dick Record<Adolf)
- [ ] Socialize with Neighborhood Assoc Leaders (virtual mtg?)
- [ ] Socialize w/ Tribune (mention Adolf"s 2014 op ed on civility; understand options w/ them
- [x] FB post(s) to EnCiv Facebook page

Upload the recorded candidate conversation on social media

**Comment by ddfridley** [comment]
We have two candidates for Onalask Mayor. Will and Adolf are working on getting these out on social media.

**Comment by MMitsuyasu** [comment]
Here's a [Google doc for drafting social media posts](https://docs.google.com/document/d/1SH5mRe-JflxF17b7QXyuhMdKvXlpeV9tj2x5YVjhP-Q/edit?usp=sharing).

Here's the [Google sheet Will & Adolf are using to track publicity contacts](https://docs.google.com/spreadsheets/d/10cGcJkZm_McjtM2aKMb0md736MCgOZhpbmYf0JlNBRE/edit?usp=sharing).
