### ISSUE TITLE
Social Media Invitation Campaign

### ISSUE THREAD

**Issue by MMitsuyasu** [EnCiv/undebate#117]
Will Ferguson (EnCiv CEO) has local contacts in La Crosse, WI who are willing to help get the word out.

It would be helpful for us to prepare some draft materials for them to post:

- **Nextdoor** seems to be a good option because it’s a location-centric social platform.
- **Facebook** has a larger reach, but depends on individual connections, though there may be relevant groups.
- **Reddit** ??

**Nextdoor & Facebook materials**
- [x] Check on information needed for posts
- [x] Draft [suggested materials for post](https://docs.google.com/document/d/1PaUoz9lub0r07JtDKFNI7vy85JPjt4a4k4M_uheIfCY/edit?usp=sharing) (@MMitsuyasu)
- [x] Collect [relevant image](https://drive.google.com/file/d/12W7UDDWGrjME1pX-9BDnbDxV7Kj7z2gf/view?usp=sharing) to accompany Nextdoor post (@MMitsuyasu)
- [x] Feedback by team
- [x] Prep version of materials to share directly with local partners
- [x] Share with local partners

**Reddit materials**
- [x] Check on information needed for posts
- [x] Draft suggested materials for post
- [x] Collect [relevant image](https://drive.google.com/file/d/12W7UDDWGrjME1pX-9BDnbDxV7Kj7z2gf/view?usp=sharing) (if needed) to accompany post (@MMitsuyasu)
- [x] Feedback by team
- [x] Prep version of materials to share directly with local partners
- [x] Share with local partners

**Comment by MMitsuyasu** [comment]
Hey all, I could use feedback on the draft [Nextdoor post materials](https://docs.google.com/document/d/1PaUoz9lub0r07JtDKFNI7vy85JPjt4a4k4M_uheIfCY/edit?usp=sharing).

**Comment by MMitsuyasu** [comment]
Nextdoor and Facebook materials are ready to share.
Please send THIS link to local partners: 
https://docs.google.com/document/d/1fvwp5Y5ZFxIvXFlKn8JK6K2XfsJmblG30W4Dsd2r-gE/edit?usp=sharing

**Comment by MMitsuyasu** [comment]
@ddfridley and @poornaraob, what do you think about skipping Reddit this time around?

With Will making personal contacts, that might be enough, and it will allow us to gain more familiarity with how Reddit works for future implementation.

If that sounds like a plan, I think this issue can be closed.

**Comment by ddfridley** [comment]
This was done.  But we don't have much of a way to track it.  One idea for next time is that with the SF DA link that we usually include, we add some sort of tracking tag so we can trace it back.
