### ISSUE TITLE
Prep standard Klaviyo email template (rich HTML)

### ISSUE THREAD

**Issue by MMitsuyasu** [EnCiv/undebate#120]
To ensure consistency with branding and format, it would be ideal to set up a reusable template style in Klaviyo

- [x] Explore options in Klaviyo (@MMitsuyasu)
- [x] Draft a template layout that would support our standard invite email (@MMitsuyasu)
- [ ] Get feedback on layout from team

**Comment by MMitsuyasu** [comment]
Here’s a look at how things would appear to a recipient (with relevant text replaced, of course)

![Klaviyo email template draft 1](https://user-images.githubusercontent.com/60209605/77835665-3884e080-710c-11ea-9b78-c26857d8c52e.jpg)

![Klaviyo email template draft 2](https://user-images.githubusercontent.com/60209605/77835667-3b7fd100-710c-11ea-9a72-e8bae091db8a.jpg)

**Comment by MMitsuyasu** [comment]
And here’s a look showing the merge tags (so you can see which information Klaviyo pulls directly from the user profile)

I’m pretty sure I’ve figured out how to get the “Record Now” button to direct to the “Recorder URL” listed in each person’s profile too.

![Klaviyo email template draft (merge tags)](https://user-images.githubusercontent.com/60209605/77835682-5ce0bd00-710c-11ea-98fc-8a8ae24ee039.jpg)

**Comment by MMitsuyasu** [comment]
And here's a version using the new Undebate logo and color scheme.

![Klaviyo email template Undebates draft 1](https://user-images.githubusercontent.com/60209605/78091600-3330cb80-7382-11ea-88dc-41f44d8bf21e.png)
![Klaviyo email template Undebates draft 2](https://user-images.githubusercontent.com/60209605/78091610-3926ac80-7382-11ea-8bfd-d39a818168ed.png)

**Comment by poornaraob** [comment]
@ddfridley @djbowers @epg323 @poornaraob - Review and provide feedback to the email structure & content before 04/07/2020

**Comment by poornaraob** [comment]
Good.
