### ISSUE TITLE
When redoing a recording, give a 3 seconds warmup

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate#126]
When users stops a video, and then hits redo, or when user just hits redo, give them a 3 seconds countdown before starting the recording.

**Comment by poornaraob** [comment]
Will move it to state. Prefer to do pair programming to review this before implementing. Mon Daivd / DJ will work together on this.

**Comment by djbowers** [comment]
I just finished up a session with David to go over current progress and review changes so far. I have a branch open [here](https://github.com/EnCiv/undebate/tree/3-sec-warmup) with those changes. I have the following tasks remaining on this issue:

- [ ] create a few designs in Figma for the warmup timer and get approved by David
- [ ] update the styles to indicate warmup
- [ ] do not run the warmup countdown during regular flow, only on rerecord
- [ ] finished speaking button should be greyed out until warmup countdown is over

**Comment by poornaraob** [comment]
05/20: 
Refactoring of code completed. 
Awaiting for review feedback from @ddfridley
