### ISSUE TITLE
Investigate on creating landing page for the student election

### ISSUE THREAD

**Issue by poornaraob** [EnCiv/undebate#135]
Investigate on creating a landing page for the Bruins student election. It must include the listing of candidates running for 15 offices. 

- [ ] UI landing page for portrait mode (Tile format)
- [ ] UI landing page for horizontal mode (Tile format)
- [ ] UI landing page for portrait mode (Listing format)
- [ ] UI landing page for horizontal mode (Listing format)

Further, On clicking specific candidate from the list, the page will direct to the conversation page (present candidate conversation recorded page)

**Comment by poornaraob** [comment]
Bruce already has a landing page for student election. They will directly use our link of recording

**Comment by ddfridley** [comment]
same as #138
