### ISSUE TITLE
Investigate on developing the landing page interface

### ISSUE THREAD

**Issue by poornaraob** [EnCiv/undebate#138]
Investigate on creating a landing page for the Bruins student election. It must include the listing of candidates running for 15 offices.

 UI landing page for portrait mode (Tile format)
 UI landing page for horizontal mode (Tile format)
 UI landing page for portrait mode (Listing format)
 UI landing page for horizontal mode (Listing format)

Further, On clicking specific candidate from the list, the page will direct to the conversation page (present candidate conversation recorded page)

**Comment by ddfridley** [comment]
Bruce has a landing page, and they are going to add links to undebates to that.
