### ISSUE TITLE
Slack to Github integration for undebate

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate#146]
https://slack.github.com/

**Comment by poornaraob** [comment]
Waiting on details for integration. 
What triggers are needed to be included. 
The notifications will be in Undebate channel for time being. We can rethink in future if we want to have a separate channel for this.

**Comment by djbowers** [comment]
Default configuration options are listed here: https://github.com/integrations/slack#configuration

We can subscribe or unsubscribe from individual notifications with 
```
/github subscribe Enciv/undebate [feature]
/github unsubscribe Enciv/undebate [feature]
```
