### ISSUE TITLE
Show the Questions in the Candidate Recorder Landing Page

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate#148]
When candidates are referred to the recorder page (from Bria) they want to know what the question are.  

If you go to  https://undebate-qa.herokuapp.com/candidate-conversation-candidate-recorder  -- or it might be schoolboard-conversation-..  if you haven't updated to the latest iota.json that's the first page they see.

Its in app/components/CandidatePreamble

the question that are going to be asked are passed to app/components/webComponents/Undebate as this.props.participants.moderator.agenda

it looks like this:
```
"agenda": [
            [
              "Introductions",
              "1- Who you are",
              "2- Where you are",
              "3- One word to describe yourself",
              "4- What office you are running for"
            ],
            ["What type of skills should students be learning for success in the 21st century?"],
            ["Closing Remarks"]
          ],
```
Also, the last item in the agenda isn't a question for the candidate to answer - it's the moderator getting in the closing statements.

I think it would also be useful to incorporate the time limits, which is also in this.props..participantes.moderator.timeLimits
```
          "timeLimits": [10, 60, 60]
```
So the task is to incorporate the questions and timelimits into the UI design and update these components to implement that.

**Comment by ddfridley** [comment]
So I see that undebate.jsx is going to give you a problem if you want to go outside the screen from within CandidatePreamble.  The render looks like this:
```
    return (
      <div
        style={{ fontSize: this.state.fontSize }}
        className={cx(classes['wrapper'], scrollableIframe && classes['scrollableIframe'])}
      >
        {this.props.participants.human && <ReactCameraRecorder ref={this.getCamera} />}
        <section
          id="syn-ask-webrtc"
          key="began"
          className={cx(classes['innerWrapper'], scrollableIframe && classes['scrollableIframe'])}
          style={{ left: this.state.left }}
          ref={this.calculatePositionAndStyle}
        >
          <audio ref={this.audio} playsInline controls={false} onEnded={this.audioEnd} key="audio"></audio>
          {main()}
          {((this.participants.human && (this.state.preambleAgreed || opening.noPreamble)) ||
            !this.participants.human) &&
            !bot &&
            beginOverlay()}
          {this.participants.human && !opening.noPreamble && !intro && !begin && !done && (
            <CandidatePreamble
              subject={this.props.subject}
              bp_info={this.props.bp_info}
              agreed={this.state.preambleAgreed}
              onClick={() => {
                logger.info('Undebate preambleAgreed true')
                this.setState({ preambleAgreed: true })
                noOverlay && this.beginButton()
              }}
            />
          )}
```
classes.wrapper is going to set the width and height, but scrollableIframe sets the height to auto.  I think it would be okay to say something like:
```
    const ifPreamble=()=>this.participants.human && !opening.noPreamble && !intro && !begin && !done 
    ...
    className={cx(classes['wrapper'], ( scrollableIframe || ifPreamble() ) && classes['scrollableIframe'])}
   ...

   { ifPreamble() && <CandidatePreamble
   ...

```
It's not beautiful but it gets there until we refactor.  One not obvious point is that to play video with audio the user has to first click on something on the page.  If the preamble was it's one page, that after clicking on next forward to the page with the video on it, then the user would have to click on another button on that page.

**Comment by MrNanosh** [comment]
I'll take another look at undebate's role in my preamble solutions but I think it is otherwise solved by the modal.

**Comment by ddfridley** [comment]
The modal isn't terrible.   I'd pull the beginButton class config for the button, but give it a different color.   But I'd rather the candidate didn't have to take an action to see the questions.

**Comment by poornaraob** [comment]
Waiting for review with David. Refactor to have scroll property. 

- [ ] Style the scroll bar transparent/replace. 
- [ ] Make the title to shrink to space

**Comment by poornaraob** [comment]
@MrNanosh , @ddfridley In the questions listing in candidate recorder landing page (shared on slack), I found an extra content after second question : 1 Look into camera while listening to example speaker as your placeholder video is recorded" is that needed?
Also, there is numbering 1, 2 added in the display of questions.

**Comment by ddfridley** [comment]
Had a problem on heroku with losing the css formating of the recorder buttons.  Converted the CandidatePreamble component to functional and used useCreateStyles from React-jss.

Worked with BP to agree to this rendering: 
![image](https://user-images.githubusercontent.com/3317487/82156855-bfb02400-9832-11ea-80d8-f8455ea8fed4.png)
