### ISSUE TITLE
Error Boundry

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate#160]
Files like app/components/undebate have an ErrorBoundary wrapper.
The error boundary wrapper should be moved up into app/components/app so that its done for all pages.
when NODE_ENV is development it should be a detail oriented page like it is now.
when NODE_ENV is production is should be a nice looking page that says sorry there was an error and does not give great detail - but logger.errors the error message
and on the browser side, when window.env is set to the value of NODE_ENV.

**Comment by poornaraob** [comment]
Implemented in #169
