### ISSUE TITLE
Hartford Landing Page

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate#178]
We are working with the Hartford Vota Colition to create a place to engage voters with candiates before elections.  The coalition will drive voters to a landing page, to get them signed up and keep them engaged.

Google slides for this can be found here: https://docs.google.com/presentation/d/1zZEYOkUG5Pbuzk0uyI9fbsjtUKy4hUVbvwX5AiDyr8E/edit?usp=sharing

**Comment by tianchili11** [comment]
https://xd.adobe.com/view/21d53bf3-a076-4a2a-417a-f6210ee98ced-57e4/
Version 1

**Comment by ddfridley** [comment]
What I see right now for Hartford is that there will be at most 5 senate office elections, each with 2 or 3 candidates, and 13 general assembly office elections, each with 2 or three candidates.   It may be less if there are no challengers to an incumbent. 

I looked at these pages: 
https://en.wikipedia.org/wiki/Connecticut_House_of_Representatives https://en.wikipedia.org/wiki/Connecticut_State_Senate

Then, if we get a voter's address and figure out where they are, there will be one senate office election, and one general assembly office election to vote in for that voter.

The office names will come from the BP data we are given, seem to be like this:
Connecticut State Senate District 1
Connecticut House of Representatives District 72

See this link: https://ballotpedia.org/Connecticut_state_legislative_districts

**Comment by ddfridley** [comment]
Here is a sample ballot for Hartford's primary election in 2018. https://portal.ct.gov/-/media/SOTS/ElectionServices/Town_Ballots/2018/Primary/HARTFORD-CT-DEM-081418.pdf?la=en

Notice there are several districts - on page for each district.   We are only talking about undebates for the State Representative - not Governor, etc.  I don't know how state representative translates into House of Representatives of Senate, and why there is only one.

**Comment by tianchili11** [comment]
https://xd.adobe.com/view/054b4d5c-4c5a-49b1-5b5e-ffe30c382a8f-737a/
Version 3

**Comment by poornaraob** [comment]
06/10: We created a new project to work on the tasks for Hartford election. So, closing this action
