### ISSUE TITLE
Develop a portrait mode UI version for landing page

### ISSUE THREAD

**Issue by poornaraob** [EnCiv/undebate#199]
It is important to have UI for both landscape and portrait mode view of the landing page at the initial stage of development of the functional wireframe of the landing page. 

- [x] Design is expected to be made available to developer by 05/29/2020 (Friday)

**Comment by tianchili11** [comment]
https://xd.adobe.com/view/054b4d5c-4c5a-49b1-5b5e-ffe30c382a8f-737a/
Portrait mode is ready to review. It's on the second page.

**Comment by poornaraob** [comment]
07/24: Looks good. We can create issue if we come up in future.
