### ISSUE TITLE
Assets and links for functional components on landing page to be supplied to developer

### ISSUE THREAD

**Issue by poornaraob** [EnCiv/undebate#200]
- [ ] The URL for the respective iframes used in UI design are to be provided to developer
- [ ] Assets and links are needed for FAQ's, How & Where to Vote, Contact Us

**Comment by tianchili11** [comment]
https://xd.adobe.com/view/10428adb-6b09-4826-7d31-95c93f070b37-6673/
Blue and white version. Click on the assets will show all the info for developers.

**Comment by poornaraob** [comment]
06/10: Enciv and Candidate conversation logo asset is needed. Make it as 1 logo asset. png or svg format file. Tracy will send it later David and Dana.

**Comment by tianchili11** [comment]
https://drive.google.com/file/d/1m5dAef_7_7QC5cPZG__4he73mdUT__yn/view?usp=sharing
