### ISSUE TITLE
Candidate didn't know the time alloted

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate#203]
We had candidate feedback that: "I didn't know before hand how much time I would have for my answers."

We should add the time alloted, next to the question in the preamble page.

in app/components/web-components/undebate.jsx
this.props.participants.moderator.timeLimits is an array of the time limits, in seconds for each question. 
for example:
          "timeLimits": [
            15,
            60,
            60,
          ]

Lets show that on the app/components/candidate-preamble as something like:

Questions for Candidates
A. Introductions **15 seconds**
1- Who you are
2- Where you are
3- One word to describe yourself
4- What office you are running for
B. What type of skills should students be learning for success in the 21st century? **60 seconds**
C. Closing Remarks **60 seconds**

**Comment by ddfridley** [comment]
localhost:3011/candidate-conversation-candidate-recorder is where you can see this.

**Comment by poornaraob** [comment]
07/01: Thong is working on this task. Will work on rendering the timer following different approach
