### ISSUE TITLE
Scorecard for all candidates

### ISSUE THREAD

**Issue by poornaraob** [EnCiv/undebate#210]
We need to work on the frame work for soft launch (1-Jul)
There are few new links requested by Hartford team like scorecard tab in page(pdf file/ form for people to know about the candidate in writing for them to refer later)
There are few sample files available in link about the scorecard. David will share in link

Hartford want links to file (name of candidate) to direct them to ballotpedia to know more info of candidate.

**Comment by ddfridley** [comment]
[City Council Candidate Review Sheet 2019 Hartford Votes-2.pdf](https://github.com/EnCiv/undebate/files/4762349/City.Council.Candidate.Review.Sheet.2019.Hartford.Votes-2.pdf)

**Comment by ddfridley** [comment]
[Mayoral candidate worksheet 2019.pdf](https://github.com/EnCiv/undebate/files/4762353/Mayoral.candidate.worksheet.2019.pdf)

**Comment by poornaraob** [comment]
06/17: Hartford is working on this. Mostly it will be a pdf file that will be included into the assets. Last week we have started with spreadsheet file to review the tasks. Will try to link it to this task.

**Comment by poornaraob** [comment]
06/24: Reviewed the details with Hartford team. They are working on this task.

**Comment by poornaraob** [comment]
07/01: Working with Hartford team. Yet to receive an update from them.

**Comment by ddfridley** [comment]
[General Assembly 5th House District Primary - Candidate Overview August 11 2020.pdf](https://github.com/EnCiv/undebate/files/4997309/General.Assembly.5th.House.District.Primary.-.Candidate.Overview.August.11.2020.pdf)

This pdf file should be put in assets/pdf

the button for it should say "Rank the Candidates" at the top of the hartford page.

**Comment by MrNanosh** [comment]
Done. location has been named hartfordScoreCards.pdf and is in assets.
