### ISSUE TITLE
FAQ Page is needed to be developed

### ISSUE THREAD

**Issue by poornaraob** [EnCiv/undebate#214]
We need a FAQ page to be developed for adding few answers to frequently asked questions regarding the undebate candidate conversation process. 
Hartford will provide the content for FAQ - (To be done by 1-Jul-Medium priority)

**Comment by poornaraob** [comment]
06/17: Dana is working on this task of creating FAQ page. We will call the web component "FAQ" and route will be called "/hartford/faq".

**Comment by MrNanosh** [comment]
completed a working FAQ page. Needs testing and additional work should be done to ensure it works well on all screen sizes.

**Comment by poornaraob** [comment]
07/24: Few feedback from Hartford:
1. There are few content from Ballotpedia page. 
2. A list of FAQ is provided by Hartford team. Link for the same is:

https://docs.google.com/document/d/1edEScHjZwuBhzTJL6xIdqlfrIbEDPI54CRzcQ30f1y0/edit#

**Comment by poornaraob** [comment]
07/01: We will be closing this task and open a new task to complete below actions:
- [ ] We need to support Bold, bullets and URL's 
- [ ] Should it be markdown or html is to be finalised - Dana / David
