### ISSUE TITLE
Google form for "Ask your Question" content

### ISSUE THREAD

**Issue by poornaraob** [EnCiv/undebate#215]
On Clicking "Ask your questions" tab on landing page, it should direct the voter to a google form with options to list their questions

The format and structure of the form to be reviewed with Hartford. 

Once the google form is updated by voters, let Hartford make consolidation of questions to come up with actual QA list

**Comment by ddfridley** [comment]
Here is the form: https://docs.google.com/forms/d/e/1FAIpQLSfsiGMaBQWnb07xyZN6wfxFZtqiEgljyevuJw4ntov4J8P7xg/viewform

**Comment by poornaraob** [comment]
06/24: Sending link to Hartford to review it.

**Comment by poornaraob** [comment]
07/01: Its reviewed and updated by Hartford. we will close this task
