### ISSUE TITLE
Need UI/UX to display a validation message for voters

### ISSUE THREAD

**Issue by poornaraob** [EnCiv/undebate#219]
Need UI/UX to display a validation message in some sort of useful way to communicate with voters

**Comment by tianchili11** [comment]
https://xd.adobe.com/view/054b4d5c-4c5a-49b1-5b5e-ffe30c382a8f-737a/
The dropdown bar gives feedback, "Address Not Found" " You are in District 3"

**Comment by poornaraob** [comment]
07/01: Work in progress. Tracey and Dana to work on the flow of the information in this week. @tianchili11 @MrNanosh Andelino

**Comment by adelinepetty** [comment]
Per meeting with @MrNanosh @tianchili11. Thanks Tracy for the designs! 

As a user, I want to enter my address to find out my district so I can watch the relevant Candidate Conversations. 

[Designs](https://xd.adobe.com/view/054b4d5c-4c5a-49b1-5b5e-ffe30c382a8f-737a/)

[Idle state](https://xd.adobe.com/view/054b4d5c-4c5a-49b1-5b5e-ffe30c382a8f-737a/screen/9cca950b-dc82-45b3-86e6-5ef7ea50ccd1/Landing-Page-Blue-4)
- Placeholder text in Address bar "Ex. 1234 Main St. Hartford CT"
- Add "Please type in your full address to locate your district" below address bar
- When user clicks into address bar, placeholder text disappears

[Submit search](https://xd.adobe.com/view/054b4d5c-4c5a-49b1-5b5e-ffe30c382a8f-737a/screen/4a999ff0-fc4a-4634-bf9c-3c1e147b626e/Landing-Page-Blue-5)
- If user enters by typing address, clicking "Find your search" button will initiate search

[Loading State ](https://xd.adobe.com/view/054b4d5c-4c5a-49b1-5b5e-ffe30c382a8f-737a/screen/3d20ba08-f0d4-4cb7-9b69-1ce6b4a8e47e/Landing-Page-Blue-2)
- When search is initiated, display the loading state with text "We are locating your district..." below search bar 

[Error State ](https://xd.adobe.com/view/054b4d5c-4c5a-49b1-5b5e-ffe30c382a8f-737a/screen/492d3218-ab34-41c3-9651-4a7338e9612a/Landing-Page-Blue-1)
- If the address is not found, display error state text "Sorry, we cannot find your address."
- Error state text disappears when user clicks inside address bar to enter a new address

[Success State](https://xd.adobe.com/view/054b4d5c-4c5a-49b1-5b5e-ffe30c382a8f-737a/screen/e4b09ce8-bb4f-4bd2-adeb-35a6ef06c86e/Landing-Page-Blue-3)
- If address is found, display to user result text "You are in district {x}" to show their correct district 
- If user clicks other Districts tabs, continue to display the result text until user reloads or exits the page 
- Change displayed tab to user's relevant district 
- Enable ease in/out animation to correct tab (per prototype)

**Comment by tianchili11** [comment]
Thank Adeline for the clear and organized statement.
 I just cleaned up the design a little bit. Here are the new links to different states.

- Idle State [https://xd.adobe.com/view/054b4d5c-4c5a-49b1-5b5e-ffe30c382a8f-737a/](url)

- Loading State [https://xd.adobe.com/view/054b4d5c-4c5a-49b1-5b5e-ffe30c382a8f-737a/screen/1818255e-28be-4781-b082-b2174ad2c2a2/Hartford-Landing-Page-locating](url)

- Error State [https://xd.adobe.com/view/054b4d5c-4c5a-49b1-5b5e-ffe30c382a8f-737a/screen/5ff71f5b-7089-4348-8ff3-4704d09a6aa9/Hartford-Landing-Page-Address-not-found](url)

- Success State [https://xd.adobe.com/view/054b4d5c-4c5a-49b1-5b5e-ffe30c382a8f-737a/screen/16d6be7f-a373-4e13-bc43-ae9d2c746968/Hartford-Landing-Page-idle-state-6](url)

**Comment by MrNanosh** [comment]
All three states were created with some minor changes and animation improvements

**Comment by poornaraob** [comment]
07/08: Feedback on development:
1. Align the address and error message to same start point
2. Grey color to be fine tuned

**Comment by tianchili11** [comment]
07/09: Updated the new design, relocated the "find my district" section on the top of the hero section. Please refer to the design as in the link. Page name: **Hartford Landing Page_layout_V2**
https://xd.adobe.com/view/10d56feb-0e4d-49df-772d-f0f2dc06d4c3-66e4/

**Comment by poornaraob** [comment]
07/15: Dana to remove the console log and close this task  @MrNanosh

**Comment by poornaraob** [comment]
07/22: Close this task. Console log clean up is to be added to new task. @MrNanosh @ddfridley
