### ISSUE TITLE
Hartford FAQ in Spanish

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate#220]
I received the FAQ translated into spanish - 
See updated FAQ in comments below

Tasks needed to be completed in Spanish transcription: 

- [x] Spanish for FAQ

Refer to Spanish Language support speech & text transcript
#217 for more details as this is extension to that task.

**Comment by poornaraob** [comment]
07/01: Will discuss on this task during hackathon on 07/02 at 2.00p.m @ddfridley @epg323 @luiscmartinez @MrNanosh

**Comment by poornaraob** [comment]
07/08: Updated FAQ is available to work on Spanish. 

Reference Spanish translation: FAQs for Hartford Voters Spanish.docx

**Comment by ddfridley** [comment]
Here is the translation of the FAQ into Spanish:

https://docs.google.com/document/d/1bUXMVlMhqQ5OaWz4R-zqXOJ2zOSo8heJkrppO3dihe8/edit?usp=sharing

**Comment by poornaraob** [comment]
07/15: Tasks to be completed under this ticket:

- [ ] Create FAQ page for Spanish. Take the iota for FAQ, make a duplicate of that record and replace English text to Spanish text. 
- [ ] Put in the button to switch from English to Spanish (below the banner).
