### ISSUE TITLE
Hartford FAQ needs styles and links

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate#224]
The Hartford FAQ answers need to have some style, like bold, and links.   We can put simple html in the faq answer props, and we can use ReactHtmlParser to parse it and make sure it's safe: 
https://www.npmjs.com/package/react-html-parser

**Comment by MrNanosh** [comment]
FAQ contents entered and parsed as html

**Comment by ddfridley** [comment]
@MrNanosh this has update content for the FAQ
https://docs.google.com/document/d/1Wm8yuJtDaobuxoNHvohubtJ2yG4BEwrhLUCYpQaslN4/edit

**Comment by poornaraob** [comment]
07/08: Need the font size and styles of FAQ to be aligned and maintained
Questions: Libre Franklin (B) 2M & Answers: Libre Frankline (R) 1.5M

**Comment by MrNanosh** [comment]
David and I worked on it this weekend and made some changes to typography as we were working on it.

**Comment by poornaraob** [comment]
07/15: Completed.
