### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate#225]
Hartford needs an About Page -,

The page should have a header and title similar to the FAQ and it should have this text: 

In response to the current pandemic, the following organizations have collaborated to develop this site to keep Hartford’s residents and their candidates for elected office safe and informed

**Hartford Votes~Hartford Vota Coalition**

The Hartford Votes/Hartford Vota Coalition includes thirteen organizations and agencies that work together to increase voter engagement in Hartford CT.  The Coalition is nonpartisan. 

**EnCiv**

EnCiv is a non-profit, transpartisan organization that develops online tools for citizen engagement.  EnCiv's Candidate Conversation tool is being made available on Ballotpedia's website.   

**Ballotpedia**

Ballotpedia is the digital encyclopedia of American politics and elections. Ballotpedia connects people with politics by changing the way they access the information they need to be informed about federal, state, and local politics. Ballotpedia currently has over 303,000 encyclopedic articles and offers daily, weekly, and monthly email newsletters on a variety of specialized topics.

 

Questions:  HartfordVota@gmail.com

**Comment by poornaraob** [comment]
07/08: Dana working on this. There are few feedback from Hartford to include logos in About page.

**Comment by ddfridley** [comment]
This is the ballotpedia logog: https://ballotpedia.org/wiki/skins/Ballotpedia/images/bp-logo.svg

**Comment by MrNanosh** [comment]
I've included the logos in the about page but I think that the sizing may be an issue. all three logos are mismatched dimensions and this results in odd seeming design. It may be better to place all of the logos between the header and their respective paragraphs in a way that broke up text better too.

**Comment by ddfridley** [comment]
The other two logo's need to have the white space around their image 
clipped.  I think there's a way to do this with CSS

https://stackoverflow.com/questions/34228043/css-crop-image-top-and-bottom

But my early attempts have left me with a great big ballotpedia logo at 
the bottom for the page.  Either we clip them with CSS or we create 
copies of the files and clip them with adobe - but it would be better 
not to have to have additional copies.

But what you are doing by creating a div with height in em's and width: 
auto looks like the right thing.

Also - given that the logos are essentially the titles of the 
organizations - it might (might meaning ask others) look better to just 
have bigger logos and not org titles.

**Comment by poornaraob** [comment]
07/15: The size of the logo needs to be fine tuned (Ballotpedia logo, Hartford logo). Enciv logo doesn't need any modification. 
Ballotpedia logo and Hartford logo needs clipping either in CSS format. 
Remove headers and adjust logo image sizes. @MrNanosh

**Comment by poornaraob** [comment]
07/22: Accepted by Hartford team. Moving to testing

**Comment by ddfridley** [comment]
Need to be able to transcribe a whole conversation
