### ISSUE TITLE
mLab is going away from Heroku Nov 10th - we need a replacement

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate#227]
We can move to Atlas from Mongo, or we can look into ObjectRocket that is on heroku.  We will need to update the doc/Install.md instructions as well.

**Comment by epg323** [comment]
I found a great chart at the bottom of this article --> https://studio3t.com/knowledge-base/articles/cheap-free-mongodb-hosting/ .

**Comment by ddfridley** [comment]
Install instructions. pull generated.
