### ISSUE TITLE
Create project card for Undebate in HackforLA website

### ISSUE THREAD

**Issue by poornaraob** [EnCiv/undebate#23]
### Overview
Provide collateral for the HackforLA website

### Action Items
- [x]   Gather items
  - [x]  600 x 400 image
  - [x]  Alt image text
  - [x]  Name of project
  - [x]  A blurb about your project
  - [x]  Links (website, github, etc.)
  - [x]  What you are looking for skills wise
  - [x]  Partner(s)
  - [x]  Location
- [ ]   Add project Card to website

### Resources/Instructions
See project cards on the hackforla.org website for examples

**Comment by ddfridley** [comment]
@poornaraob  Can you help with this?  How do we add a project card to website?  See if you can use the image and blurb from https://github.com/EnCiv/undebate as a start.

**Comment by ddfridley** [comment]
Image:
![undebate-image](https://user-images.githubusercontent.com/3317487/70661587-76233380-1c19-11ea-8800-f6b9d71fa5e7.jpg)
**Alt image text:**
Undebate with moderator and 7 participants
**Name of Project:**
undebate
**A blurb about your project:**
Not debates, but recorded online video Q&A with candidates so voters can quickly can get to know them, for every candidate, for every election, across the US.
**Links:**
github: https://github.com/EnCiv/undebate
demo: https://undebate.herokuapp.com/san-francisco-district-attorney
**What you are looking for skills wise:**
Node, React
**Partner(s)**
EnCiv.org, Ballotpedia.org
**Location:**
Santa Monica + Remote

@ExperimentsInHonesty

**Comment by ddfridley** [comment]
![undebate-hackForLA](https://user-images.githubusercontent.com/3317487/71294699-1ff77400-232e-11ea-9c88-3b3320486eb3.jpg)

@ExperimentsInHonesty  here is a revised image, what do you think?

**Comment by ExperimentsInHonesty** [comment]
This has been added to the [hackforla.org](http://hackforla.org/) website
<img width="1411" alt="Screen Shot 2020-01-03 at 1 43 36 AM" src="https://user-images.githubusercontent.com/37763229/71716722-866aa080-2dca-11ea-9aea-7437a499eb01.png">

@ddfridley please confirm that the information displayed is correct.

**Comment by ddfridley** [comment]
Look great!
