### ISSUE TITLE
Parameterize Agenda Type for Candidate Conversations

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate#234]
We need to be able to move forward with having transcriptions, without having to bulk support transcription in all past and current elections.  We need to be able to iterate on transcriptions, and how they are shown withing the agenda 

Proposed Solution:

add an agendaType to props that specifies AgendaTranscribe as the agenda to use.  
If agendaType is not present/ not specified then it defaults to AgendaBasic

Then, for the cases we want to transcribe we can set agendaType, but for all existing cases it can work as it does now.

**Comment by poornaraob** [comment]
07/22: No significant progress. Work in Progress.
