### ISSUE TITLE
Hartford Changes 2020Jul22

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate#235]
In the review today the focus was on the issue that we only have candidates for one district, and that when people first come to the page they don't have a good idea why they should enter their district.   The decision was to show them the one candidate conversation in place of the Hartford picture so that they would see what it's about without having to scroll down.   

- [x] Text for enter you address to "Enter your address to meet the candidates in your district." - 
- [x] Hartford Votes text goes away and the Meet Hartford's candidates .... becomes the big text at the top
- [x] The 3 panel Hartford picture goes away and the stuff below moves up
- [x] "Have questions for the candidates" and [Click here to ask Questions] moves to just below the conversation or placeholder
- [x] "Have questions for the candidates" should be bigger and dark on the light background
- [x] The default district when someone lands here should be 5 (the one where there's a conversation)
- [x] "Coming Soon" text overlaying the image should be "Come Back for the General Election"  and that text and the "-" taken out of the line above.
- [x] "There are no State Representatives candidates in the Primary election for this district" => "There are no state representatives in the primary for this district." with a period at the end. 
- [x] Not shown - we need Spanish treatment for the Bios - translation to be provided by in a day or 2. 

![hartford-edits-2020Jul22](https://user-images.githubusercontent.com/3317487/88231185-9cd22f80-cc28-11ea-943f-7e93d699056c.png)

**Comment by tianchili11** [comment]
[New design_Hartford Landing Page](https://xd.adobe.com/view/c10b367c-028f-4bcf-8fbe-8a97c7aceaf0-9458/)
Please click to view the new design. @ddfridley

**Comment by ddfridley** [comment]
@tianchili11 @MrNanosh  I'm sorry to say this but we really need to go based on the markup in the drawing above.  That's what we reviewed in the call. It's very late in the process and introducing changes other than what's been reviewed will just create more rounds of changes.  If you need me to explain the messy mark up - I'm available.

**Comment by ddfridley** [comment]
Candidate Bios Spanish Translation
Datos biográficos de los candidatos políticos de Hartford, CT

Brandon McGee Jr.
Brandon L. McGee Jr. está cumpliendo su cuarto término en el cargo como Representante Estatal y en búsqueda de su re-elección al mismo para continuar abogando por los residentes de Windsor y Hartford en el Distrito 5 de la Asamblea Estatal.  Nacido en Hartford, Brandon se enfoca ampliamente en influenciar las políticas públicas en el estado y ha persistido en abogar por la equitatividad en la educación, la reforma del sistema judicial, la inscripción de votantes, y el empoderamiento por las personas de color y sus comunidades. El también tomó parte en la aprobación de la ley más favorable en la nación en relación al pago por tiempo para atención familiar y médica (Paid Family and Medical Leave). Brandon actualmente asume el cargo de Presidente del Comité de Vivienda así como de Vice-Presidente del Grupo de Consulta Política Afro-Americano y Puertorriqueño de la legislatura estatal. También rinde labor en el Comité de Educación y el de Servicios Humanos. Luego de obtener el Bachillerato en Alabama State University, el se graduó con Maestría en Ciencias de la Albertus Magnus College. Disponiendo de sus facultades, destrezas y experiencia, ha colaborado con sus constituyentes en numerosos organismos y juntas directivas para aumentar los recursos comunitarios, entre ellos Ascend Mentoring, BSL Education Foundation (en el cual ejerció el cargo de Presidente), Citadel of Love Church (como Díacono), Hartford Behavioral Health, y Jewish Family Services. Durante su trayectoria professional, ha recibido numerosos galardones por su labor cívica. Brandon continúa ejerciendo el puesto de Oficial Creativo en su empresa McGee Firm en Hartford, y también trabaja en Capitol Region Education Council. Actualmente reside en Hartford con su esposa y dos hijas.












Craig Stallings
Craig Stallings se distinguió como Presidente y miembro de la Junta de Educación de Hartford. Fue Presidente del PTO (Grupos de Padres y Maestros) en dos de las escuelas en Hartford y fue coordinador del concilio original de gobierno en la escuela Thirman L. Milner School. Como Presidente de la Junta de Educación, él supervisó el Proyecto de la Escuela Superior Weaver y, además, se aseguró que se aprobaran fondos para el proyecto de renovación de la MLK School, la única de su índole en el estado y la cual será inagurada en el año escolar 2020-2021. Craig es co-fundador y gerente de Stallings Tax Service LLC desde el 2006, y también trabajó como representante de servicios a los clientes en la empresa Tele-Tech, bajo contrato con Bank of America. Graduado de Weaver High School, terminó sus estudios en Capital Community College, Manchester Community College, y University of Hartford. Craig es el padre de tres varones, uno de ellos Cadete en el Departamento de Policía de Hartford y los otros dos aún estudiantes en las escuelas públicas de Hartford.

**Comment by MrNanosh** [comment]
All Done.

**Comment by MrNanosh** [comment]
hartfordFunctionalLandingPageSkeleton#196part3 to close this issue.
