### ISSUE TITLE
Candidate Friendly Preamble Page

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate#238]
We have a low conversion rate of candidates getting to the recorder page and then recording. 

https://xd.adobe.com/view/068e7499-054a-43b9-aecb-c3c6b5047d17-53dd/

**Comment by ddfridley** [comment]
@tianchili11 

I just saw page 2 and 3 in this: https://xd.adobe.com/view/068e7499-054a-43b9-aecb-c3c6b5047d17-53dd/screen/40495cd4-1449-46e7-b609-c7909e6de88d

did you add them recently or did I just miss them the first time.

This is really awesome. I left some comments.  If you can change step 2 to "Review It" - see comment on page 2 - then we should show this to Liz (marketing words expert), Will and Adolf and get some feedback on tightening the words.

**Comment by tianchili11** [comment]
[edited version](https://xd.adobe.com/view/2bb70023-e7b4-4e57-b52a-3a8a8a578c4a-7ee4/)
Please check the newly edited version.

**Comment by tianchili11** [comment]
> @tianchili11
> 
> I just saw page 2 and 3 in this: https://xd.adobe.com/view/068e7499-054a-43b9-aecb-c3c6b5047d17-53dd/screen/40495cd4-1449-46e7-b609-c7909e6de88d
> 
> did you add them recently or did I just miss them the first time.
> 
> This is really awesome. I left some comments. If you can change step 2 to "Review It" - see comment on page 2 - then we should show this to Liz (marketing words expert), Will and Adolf and get some feedback on tightening the words.

It was there at the beginning.

**Comment by ddfridley** [comment]
This could be implemented as a new Candidate Preamble component.

**Comment by MrNanosh** [comment]
@ddfridley Are we going with the designs on pages 2-3? I should have a rough iteration of these done over the weekend

**Comment by ddfridley** [comment]
@MrNanosh see the edited version that came later from Tracy - it only has 1 & 2.

**Comment by tianchili11** [comment]
@MrNanosh Please see the link for [development](https://xd.adobe.com/view/0df93087-17a5-40da-a022-043d27c96e83-58aa/).

**Comment by ddfridley** [comment]
These assets have been loaded on cloudinary: 
https://res.cloudinary.com/hf6mryjpf/image/upload/v1596687849/assets/upload.svg
https://res.cloudinary.com/hf6mryjpf/image/upload/v1596687838/assets/review.svg
https://res.cloudinary.com/hf6mryjpf/image/upload/v1596687809/assets/record.svg
https://res.cloudinary.com/hf6mryjpf/image/upload/v1596687676/assets/Group_29.png
https://res.cloudinary.com/hf6mryjpf/image/upload/v1596687563/assets/flag.png

**Comment by ddfridley** [comment]
@MrNanosh here is what we need to do to finish this out. 

- [ ] We are going to redo question D so that it doesn't have a 1, and a 2.  So you don't need to put the (seconds at the beginning)

- [ ] when the viewport is very wide, we need to put a limit the width of the content, and center it.
![image](https://user-images.githubusercontent.com/3317487/90170597-23c08680-dd55-11ea-877d-1b0470ba5ccb.png)
in Preamble .inner-content  add:
```
    max-width: 50em;
    margin-left: auto;
    margin-right: auto;
```

- [ ] Liz is going to provide new text for the tips at the bottom, and it will be bulleted.

- [ ] The date line, in the conversation header, in portrait mode, needs to be left aligned, and clipped (not hidden).

![image](https://user-images.githubusercontent.com/3317487/90169535-8e70c280-dd53-11ea-88d4-758cd462d45c.png)

In .g-rightBoxContainer-0-2-71.g-portrait-0-2-78 
```
    text-overflow: clip;
    text-align: left;
```

- [ ]  make the icons  (all 3) taller on large windows - make it 100% of it's parent height:
for example
```
<img src="https://res.cloudinary.com/hf6mryjpf/image/upload/v1596687809/assets/record.svg" height="100%" width="auto">
```

- [ ] Make the click here to start recording button function

- [ ] Create a PR we're good to go.

**Comment by MrNanosh** [comment]
I had to use a pixel value for max width in preamble inner-content to avoid having a max width at all screen sizes due to the changing value of of an em in our code. I set it to 1000px and this looked okay so if you want me to use a different value please let me know. Other than that this is done.

**Comment by ddfridley** [comment]
Great. Can you do a PR then?


⁣Get BlueMail for Android ​
