### ISSUE TITLE
 Self-service Portal for Election Leaders to Create Undebates for their Election

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate#301]
We need a way for an election leader to create undebates for the offices of the election, invite the candidates, and then provide the completed undebates to their constituents.

## Election Leaders
An election leader is the person in charge of administering the election (not a candidate). 

The election leader will get to a dedicated landing page, either sent their by clicking on a link, or by visiting enciv.org.
If they don't have an account, they will need to join.

An election leader will be able to see a list of elections they have created, and will be able to create new elections.

## Data Needed from Election Leader
- Name for the election leader's organization
- Name for the election
- Last Day of Election

- Election Table
```
Region, Office, Candidate Name, Email Address
```

- [ ]  How should the election table be provided, online form, upload a csv file, enter the data, pull from google sheet
we should pick one to begin with.

- Questions to ask the Candidates -
	Limit 280 characters - the questions should be gathered through a form. The form should show how many characters left, and prevent the entry of more characters than the limit.  The UI should also show how many seconds this is - assuming 5 characters per word, and 120 word per second. 

- Name, Email of Moderator

- Script for Moderator [example](https://docs.google.com/document/d/1_jJPRGdCkms5RQJLP_yTY9U_B1pjAxM0kViJcPFouio/edit) is available 

The script should be provided through an online form.  The script for each video segment should be a separate input form. Limit 600 characters.  The form should show how many characters left, and prevent the entry of more characters than the limit.  The UI should also show how many seconds this is - assuming 5 characters per word, and 120 word per second. 

In the form we need to provide some guidelines for content.  For example, the moderator should appreciate the candidates for answering the previous question, before asking the next question. And after the last question, the moderator should thank the candidates for participating, and thank the audience.  

The text of the questions should be included in the script.

## Steps

1. Leader provides Information Above (Election Table can come later)
2. Email is sent to Moderator with script and a recorder link we generate
3. Moderator visits link, records and posts recording
4. Leader receives Notification of Posting
5. Leader reviews Moderator Recording
5.1. Leader sends email to moderator asking them to re-record and make changes
5.2. Moderator rerecords by reusing the same link, and posts
5.3. Back to 4
6. Leader provides/updates Election Table
7. Leader approves sending invitations to the candidates
8. Leader receives email each time a candidate records which includes the viewer link to review
8.1. If Election Leader has issues with the candidates recording, the election leader contacts the candidate and asks them to rerecord.
8.2 Back to 8
9 Election Leader sends view links to voters, or embed viewer links onto their web pages, or post links to viewers in social media channels.

**Comment by ddfridley** [comment]
Kamal created this: https://www.figma.com/proto/Cd98gwn3NhjGzHDnoTI9jc/Untitled?node-id=1%3A2&scaling=scale-down-width

**Comment by procupid** [comment]
[High Fidelity Prototype](https://www.figma.com/proto/Cd98gwn3NhjGzHDnoTI9jc/Undebate?node-id=98%3A460&scaling=min-zoom&page-id=46%3A2)

**Comment by ddfridley** [comment]
@procupid @clin138 Regarding the prototype - I have a new thing to consider.  After we finish unpoll, we are going to need a self-service way for someone to create their own unpoll.  (It will be much easier than an undebate) So maybe we should think about one landing page (an EnCiv landing page), and then the user can choose to create an undebate or an unpoll, or (in the future) an untownhall, or an un.... or whatever other tools we create.   Think about it for now - we can discuss.

**Comment by ddfridley** [comment]
Here is a newer edition of the ui design:
https://www.figma.com/proto/Cd98gwn3NhjGzHDnoTI9jc/Undebate?node-id=411%3A3767&scaling=min-zoom

**Comment by ddfridley** [comment]
Latest UI link: https://www.figma.com/file/FQLXQF8WpIbmN5pV2uYc57/Undebate?node-id=1%3A3585

**Comment by ddfridley** [comment]
This is now the [undebate-ssp](github.com/EnCiv/undebate-ssp) project.
