### ISSUE TITLE
Social media share button for undebates

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate#32]
When someone is watching an undebate - we should offer them a share button.

**Comment by ddfridley** [comment]
Luis - what's the status on this? Any challenges?

**Comment by poornaraob** [comment]
facebook link: https://www.facebook.com/EnCiv.org/

**Comment by poornaraob** [comment]
Twitter link: https://twitter.com/_enciv

**Comment by poornaraob** [comment]
@luiscmartinez Please provide a quick update in the comment section with below 4 key points before today's meeting for us to review:
1. Progress
2. Challenges / road blocks
3. Expected completion date
4. Availability during the week

**Comment by poornaraob** [comment]
https://github.com/EnCiv/undebate/pull/90/commits/28bca65a84180109a39878347cad29d729e908a4

**Comment by poornaraob** [comment]
Update from 03/16 standup: the social media share button looks good. @ddfridley will review the request and provide feedback.
