### ISSUE TITLE
Node Security Review

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate#34]
This was a great article about securing Node applications.   https://medium.com/@rajapradhan08/best-practices-for-securing-node-js-web-applications-2e54cfefdc05

What of these should be applied to this project.  If something is big and should be applied, create separate issues for them.

- [ ] Apply helmet.js

**Comment by poornaraob** [comment]
We meet at 1.00p.m on 04/30 to discuss further detailing on the task.

**Comment by ddfridley** [comment]
closed by pr#168
