### ISSUE TITLE
New Viewer UI fixup

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate#50]
Refering to this in phigma: https://www.figma.com/file/jtIoqpnhGfBEAHSVLAIVf4/undebate_UI?node-id=363%3A425

And to this image:

![viewer ui markup](https://user-images.githubusercontent.com/3317487/73678785-effdf900-466d-11ea-8d89-fb9a3dde1ac8.jpg)

In figma the template is layed out as 1920x1080.   If you click on an element (like the title) it will show dimensions and details in pixels.  We need to convert those dimensions into vw or vh or rem as much as possible.  --  (except in calculate style where we are doing everything in px so that we can easially add vw's and rem's).

We looked at the font sizes and decided that 35px should be 1rem, 45px shold be 1.25rem, and 30px should be 0.85rem.  There is a place where the fontsize is calculated and set in the HTML element. 

A- The size of the blue box should be calculated in vw and vh, and rendered as a inline-block  (not a border which is taller than the text.  

B. The yellow box size should be calculated in vw and vh and rendered as an inline-block.

C. FontSize of the date should be normal.1rem

D. The video window should be taller and wider, and the text title should overlay it. Also make the black background 50% transparent.  The style.left calculations for the seats will need to be updated.  Check and use the font-family, size, weight, as described in figma

E. "Agenda" font family/size/weight also check on the height of the box.  

F: Font family/size/weight

G: Font family/size/weight

H: We should change the begin button to a bigger version of the Play button, and make the black background 50% transparent.  To do that - we will have to take the file in the svgr directory and edit it.  Make an icons directory in app/components and put it there. 

I: make all the button icons 50% transparent - put them in the new icons directory.  (The idea of the svgr directory is going to have to go away because we will have to make tweaks to the files every time.)  Unless you can think of a better way.

J: If there are fewer candidates than will fill the screen, center the row - so there is an equal amount of space on the left and right.  Depending on the aspect ration of the display, in some cases their may be white space to the right of Agenda.  In this case the Speaker+Agenda row should be centered similar to the candidate row when there are only a few candidates.
![undebate-sf-da-centered-1500x700](https://user-images.githubusercontent.com/3317487/73682186-b4b2f880-4674-11ea-8e3e-d9cfe71e7501.png)

K: In this image,
![viewer ui markup candidate count](https://user-images.githubusercontent.com/3317487/73681490-4a4d8880-4673-11ea-9243-123b74f0daa1.jpg)
If there are more candidates than will fit on the screen, add this box showing the icon, the number of additional candidates, and the right chevron.  If someone clicks on the box- scroll the candidates to the left by half the screen width.  After scrolling, show a similar box on the left, showing the number of candidates that are offscreen to the left.  You could accomplish the scroll bay creating a candidateScrollLeft state variable, and adding it to the left seats when you calculateStyle. 

L: In portrait mode, add a second row of candidates - if necessary - as in https://www.figma.com/file/jtIoqpnhGfBEAHSVLAIVf4/undebate_UI?node-id=172%3A132

Notice in landscape mode there is a calculation:
```
let calcHeight=navBarHeight+vGap+width*seatWidthRatio*HDRatio+titleHeight+vGap+width*speakingWidthRatio*HDRatio+titleHeight+vGap;
                if(calcHeight>height){ // if the window is really wide - squish the video height so it still fits
                    let heightForVideo=height-navBarHeight-vGap-titleHeight-vGap-titleHeight-vGap;
                    let calcHeightForVideo=width*seatWidthRatio*HDRatio+width*speakingWidthRatio*HDRatio;
                    seatWidthRatio=seatWidthRatio*heightForVideo/calcHeightForVideo;
                    speakingWidthRatio=speakingWidthRatio*heightForVideo/calcHeightForVideo;
                }
```
Make a similar calculation for portrait mode to make sure it all fits on the screen.  You'll also have to center the speaker and the agenda if you do this.

**Comment by ddfridley** [comment]
@beribak I have created a new branch on origin: ui-fixup#50
You should fetch this branch, and dump the reactCameraRecorder branch.

`git checkout -t origin/ui-fixup#50`

After you fetch this, do an `npm install` for good measure.

I have applied prettier, and merged in other changes, so that the only difference between this and master are the changes you have made to conversation-header.jsx and candidate-conversation.jsx
It should be for you, as it was before - but you need to check it.

You may also noticed I factored out another module - now lib/create-participant.js this is when candidate recording are uploaded.  Shouldn't effect you.

Also - checkout portrait mode when there are only 3 candidates - there's one on the bottom row and two on the top row.   I think they should all be on one row.  Probably there should be only 1 row if there are 3 candidates or less. 

Please see the new note in REAMDME.md about how to install prettier on VSC.

**Comment by poornaraob** [comment]
@beribak (Danko): Please provide a quick update in the comment section with below 4 key points before today's meeting for us to review:
1. Progress
2. Challenges / road blocks
3. Expected completion date
4. Availability during the week

**Comment by beribak** [comment]
1. The only thing that is left is adding a scroll button when the videos go off the screen.
2.  
3. 03/20/2020
4. Every day between 12pm and 7pm

**Comment by ddfridley** [comment]
![image](https://user-images.githubusercontent.com/3317487/77368620-dd24ae00-6d19-11ea-9508-0942206190d8.png)
When I render at these dimensions, the left of the speaker and the right of the agenda are being clipped off.  I think this has to do with recalculating the height of the speaking windows because it was going to be below the screen but that's a guess.

**Comment by poornaraob** [comment]
03/25: had call with Danko. Move it to Need testing. @beribak Danko will open up another issue "how to rearrange large number of things in screen"

**Comment by ddfridley** [comment]
Done in #125
