### ISSUE TITLE
Investigate how to deploy on google cloud

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate#57]
The README.md here talks about how to deploy this on heroku.  The task would be to figure out how to deploy this on google cloud and create an equivalent document. 

Ultimately we are looking for autoscaling features, and the lowest cost for our poor unfunded nonprofit.  But we need to start somewhere.

**Comment by poornaraob** [comment]
@mh-bennett : Please provide a quick update in the comment section with below 4 key points before today's meeting for us to review:
1. Progress
2. Challenges / road blocks
3. Expected completion date
4. Availability during the week

**Comment by mh-bennett** [comment]
1: Reviewed migration walkthrough by Google, contacted mLab support about migration effort requirements.
2: Busy with work
3: This Sunday 
4: Little to none

**Comment by poornaraob** [comment]
Update from 03/16 standup:
Develop demo to run on mango or mlab server. Reconnect on this action with Matt in 3 weeks time to check on the Docker file (next follow up date 04/06/2020)
Close this case and open a new issue case for docker file (Action item: Matt)

**Comment by poornaraob** [comment]
The investigation was completed by Matt. A new issue case will be updated for docker file.
