### ISSUE TITLE
Countdown time doesn't pause when recorder paused.

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate#74]
app/components/web-components/undebate.jsx

When a candidate is recording, if they hit the pause button, the recording pauses but the countdown times keeps going.    If the candidate hits pause, the countdown should go down to zero, because when they start again, it will start from a full count.  

Make sure that the Redo button is active and highlighted if paused, that's what they should do next.

**Comment by poornaraob** [comment]
DJ started to work on issue on 03/16
