### ISSUE TITLE
Can't re-record after getting to Thank You

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate#76]
In the candidate-records, after the moderator says the last part, it goes to the Thank you page automatically.  Candidate's have requested the ability to go back and rerecord from there.

This is in  app/components/web-components/undebate.jsx

To see an example of recording go to https://cc.enciv.org/schoolboard-conversation-candidate-recorder  or localhost:3011/schoolboard-conversation-candidate-recorder
Note in the latest version go to localhost:3011/candidate-conversation-candidate-recorder

UI wise we need a design for how the "Thank You" page will look with this review button on it, and generally  the Thank You page needs to look better.

**Comment by ddfridley** [comment]
Add a button in the ending() called [Review]  the button should setState somthing like {round: 0, seatOffset:0, done: false, finishUp false} but there might be some other states that need to be tweakes.  Or maybe it's a back arrow button in a box.

**Comment by poornaraob** [comment]
05/20: Work In Progress. Will be closed by next week. A new issue task will be raised for UI design to refactor (Thank you - review it)/ (login-submit screen).

**Comment by poornaraob** [comment]
05/27: This task is closed with PR #193
