### ISSUE TITLE
Force smartphones into portrait mode when recording.

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate#8]
We don't currently block recording from a smartphone, and in some cases it may work - but there are issues:
1) if the user is holding it in portrait mode it's going to look wierd when payed back along side all the other videos
2) The facial perspective is going to be different
3) If the users is holding the phone the video is going to jump around more.
Should we block recording? Should we force them into landscape mode? Should we include a warning for smartphones that says to use a stand so that you are not holding it.

**Comment by ddfridley** [comment]
Detect that someone is trying to record on a smartphone by looking at browserConfig.type
If in portrait mode - put up a message that says must record in landscape mode and prevent all other actions.
When starting to record in landscape mode, give the user an extra screen of instruction saying that the phone should be mounted on a stand for stability.

**Comment by ddfridley** [comment]
When a smartphone startes to record, if it's in portrait mode, stop/prevent recording, and put up a screen saying to rotate the phone into landscape mode in order to record.  When it gets into landscape mode. allow it to start automatically.

**Comment by ddfridley** [comment]
mostly I think you will stay in undebate.jsx but there is app/components/react-camera-recorder but that's trying to be generic.  Mostly, in undebate, do what the pause button does when the phone is turned into portrait mode, and do what the rerecord button does when the phone is turned into landscape mode.  If initially it is in portrait mode, when the user presses the begin button, handle it then.

**Comment by ddfridley** [comment]
@MrNanosh  I reviewed your draft. 

After receiving the pop-up message in portrait mode, when returning to landscape mode I'd rather just see the video (no popup with countdown).   Also, there is a new 3 second count down on rerecord feature so that would work nicely.  Being able to see myself in the video will help me get my face centered in the frame. Also, I don't see a need to have a 3 second countdown before stopping when portrait is detected. We want people to record stable video.  If it's not stable, they should redo it. 

Also, after someone hits the begin button and is in portrait mode we should let them know that they can't record in portrait mode, so that they aren't surprised when they get there.  Perhaps with the same popup that just tells them to go back to portrait mode.  

But more generally, I think that we should always stop, until they go into landscape mode but maybe we should hear from others on this one.

**Comment by poornaraob** [comment]
05/20: Changes to be reviewed by @ddfridley and provide feedback to close this.

**Comment by poornaraob** [comment]
05/27: 
There was 1 conflict in the merger process. The transition from portrait to landscape mode shows issues in multiple iterations of switching. There are two brances (8 and 8-A). 
Need to figure out the issue after merger.

**Comment by poornaraob** [comment]
06/10: Dana will review it on 06/11. #186 PR

**Comment by poornaraob** [comment]
06/17: In progress. David will look at the details and close/comment

**Comment by poornaraob** [comment]
07/01: Tested and found issue when switching back and forth between portrait / landscape multiple times, recording isn't behaving as expected (it gets confused). Probably something to do with camera.

**Comment by poornaraob** [comment]
07/08: Not worked on the fix due to other priority. David plan to work this week

**Comment by poornaraob** [comment]
07/22: No significant progress on this task.
