### ISSUE TITLE
QA e2e test environment setup

### ISSUE THREAD

**Issue by djbowers** [EnCiv/undebate#98]
Opening up this ticket to capture our work on getting started with QA automation testing. 

@ddfridley wrote out a checklist of QA e2e tests which can be found [here](https://docs.google.com/document/d/1hJ6mDjHaL5utPMgE3Za1r7FfrjF3ArRwW7vuUllx-3E/edit)

There are a few things we need to decide before getting started on these though. 

## 1) What automation tool are we going to use? 

As far as I know, there are two major UI test automation tools available right now: **Cypress** and **Selenium**. Selenium is older technology and requires a lot more knowledge, setup, and external tooling to get started. Cypress is newer and has a lot of great batteries-included features like snapshot time travel and easier debugging, but it doesn't have support for testing on as many browsers. 

Cypress used to only support testing on Chrome, but [as of Feb 6](https://www.cypress.io/blog/2020/02/06/introducing-firefox-and-edge-support-in-cypress-4-0/) it also supports Microsoft Edge and Firefox. 

@ddfridley I would prefer to use Cypress over Selenium, as there are a whole host of issues with the underlying Webdriver technology behind Selenium, including the following:

> It's slow
It's async
It's stateless
It's exposed over an HTTP server
It's a lowest common denominator
It's limited in scope and features
There are small inconsistencies
There are various driver bugs

You can read more about Cypress roadmap and why it still only has limited browser support in [this ticket](https://github.com/cypress-io/cypress/issues/310). 

So the question is: can we live without Safari support for now or is that a dealbreaker? 

## 2) Do we want to use a BDD tool to write our tests?

I'm in favor of using **Cucumber** with Gherkin syntax to write out our feature tests. This forces us to use the format of Given/When/Then when writing out our tests, which enforces good testing style and code reuse. There are packages for integrating Cucumber with both Cypress and Selenium, so these decisions are independent. 

As an example, here is a browser test written in Selenium (would be slightly simpler in Cypress)

```
const assert = require('assert');
const webdriver = require('selenium-webdriver');
const browser = new webdriver.Builder()
  .usingServer()
  .withCapabilities({'browserName': 'chrome' })
  .build();

browser.get('http://en.wikipedia.org/wiki/Wiki');
browser.findElements(webdriver.By.css('[href^="/wiki/"]'))
.then(function(links){
  assert.equal(19, links.length); // Made up number
  browser.quit();
});
```

and then here is the same test written in Gherkin. 

```
Given I have opened a Web Browser
When I load the Wikipedia article on "Wiki"
Then I have "19" Wiki Links
```

Which one is easier to read and understand? Definitely the Gherkin syntax. We would then have to define the following steps for the Gherkin to work. 

```
Given('I have opened a Web Browser', function() {});
When('I load the Wikipedia article on {stringInDoubleQuotes}', function() {});
Then('I have {stringInDoubleQuotes} Wiki Links', function() {});
```

where each function would carry out the implementation for that step. Make sense? You can read more [here](https://www.sitepoint.com/bdd-javascript-cucumber-gherkin/).

**Comment by djbowers** [comment]
Note I was considering whether or not we should use the "PageObject" model commonly employed when using Selenium and Java code. After reading [this article](https://www.cypress.io/blog/2019/01/03/stop-using-page-objects-and-start-using-app-actions/), I think that if we decide to go with Cypress, then we can use Cypress "App Actions" instead of the PageObject model. I think this is a better model for our react app since we are not really testing plain html documents, as the PageObject model was originally created for, but rather testing a dynamic web app.

**Comment by ddfridley** [comment]
I used Selenium a little bit, a few years ago.  My experience then was that it was a lot of work, so I think it's worth trying Cypress out and then evaluating it.  

Lets give Gherkin a try. 

I have three examples of test that we should figure out how to do, and it might require some changes to the code to be able to test it - but that's okay.  Design for testability.

1) Does clicking on the Begin button cause the videos to play. 
2) Do the video's rotate after the moderator finishes speaking.
3) Is user able to record and upload a video. 

As for testing on Safari - we have to do it, but we can have a small number of tests that we run manually - especially something like "Is user able to record and upload a video" - I just don't know how we are going to do it on a simulator.  But even so, this interaction is so device and browser and OS specific that I think we need to do real hands on testing to be sure. It's also something that Apple is in continuous improvement of - so it will keep changing on new releases.

So we should try cypress on Chrome and try to do the 3 things above (or less or more depending, lets discuss) and then evaluate. 

Also recording video on FF doesn't work right now, but that's lower priority.

**Comment by ddfridley** [comment]
Sounds more appropriate.  I wonder if we can look at the react state.  
We could simulate clicking on the begin button, and then wait for the 
state to change, and then after a video pays (a time out), look for the 
state to change again. Perhaps we can build in hooks for the test 
environment, so that after there is a state change, the hook gets called.

**Comment by djbowers** [comment]
The PR #110 is ready to close this ticket. I only implemented the first two of the three suggested tests:
1. Does clicking on the Begin button cause the videos to play.
2. Do the video's rotate after the moderator finishes speaking.

Also I decided to stick with just Cypress and no Gherkin for the sake of this PR. We can add a BDD tool in the future if we would like.
