### ISSUE TITLE
Join and Login improvements

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate#99]
After you go through /schoolboard-conversation-candidate-recorder and get to the Thank You page, the ui needs some quick improvements:

The Name field needs to be required

The Login and Join buttons are tiny - and should be bigger and brigher
People are confused but having Login and Join combined in one thing - lets separate these in to what look like two tabs, where Join is the initial Tab, but you can hit the Login tab.  - but actually it's just this same component with two different 'shapes', and if you type your email and password on the join tab, and then hit the login tab, your email and password are still there, and you can switch back and forth.

Start by doing a rough sketch of the UI for the Join/Login component before implementing and lets get some feedback.   But we're trying to do quick and simple at this point.

**Comment by poornaraob** [comment]
04/08: Need to work on the detailing of the issue
1. Present at logout screen "thank you", the login & Join button is aligned to either sides of screen (As-Is). Expectation is to have the Login & Join button to be more friendly and aligned center. 
2. create rough sketch of the expected UI using whiteboard app and share it with team members for review
3. Work on the coding side to improve this interface.
4. also, if I login username & password once, then the login details should be updated automatically & the curser to login button

**Comment by luiscmartinez** [comment]
I am done. Just polishing up the widths of the form.

**Comment by ddfridley** [comment]
Trouble fixing issues with growing and shrinking when viewport changes.
Working on work until this weekend. 
But its ready otherwise.

**Comment by poornaraob** [comment]
Progressing as planned. Will close by May Mid. Link the respective PR 102 to this task

**Comment by poornaraob** [comment]
Reviewed by 3. Can be closed. Works as needed

**Comment by poornaraob** [comment]
A new issue will be raised for portrait mode issue we observe in mobilephone view. @ddfridley David will do it in coming week.
